require 'teambition-icon-fonts/css/teambition-ui-icons.css'

exports.Copyarea = require './module/copyarea'
exports.Switcher = require './module/switcher'
exports.Wheeling = require './module/wheeling'
exports.SearchBox = require './module/search-box'
exports.SwitchTabs = require './module/switch-tabs'
exports.LoadingMore = require './module/loading-more'
exports.ColorChooser = require './module/color-chooser'
exports.ImageLoading = require './module/image-loading'
exports.LoadingCircle = require './module/loading-circle'
exports.LoadingIndicator = require './module/loading-indicator'
